[build-system]
requires = [
    "setuptools",
    "webrtcvad",
    "webrtcvad-wheels",
    "packaging",
    "importlib-metadata",
    "requests",
    "typing-extensions",
    "librosa",
]
build-backend = "setuptools.build_meta"